### ISSUE TITLE
unloading before url change "chrome"

### ISSUE THREAD

**Issue by The-Code-Monkey** [tkloht/react-video-cover#178] opened 2018-05-17 14:07 UTC
Im using chrome and when i change url the video unloads before the route changes.

which is causing a really annoying flash on my screen.

it doesnt do this on firefox as firefox seems to pause the video

**Comment by tkloht** [comment] 2018-06-05 12:53
sorry i totally missed your issue - will try to look into this later tonight.

**Comment by mikejernil** [comment] 2019-03-26 13:32
@tkloht hey any update on this issue? I'm facing the same problem

**Comment by tkloht** [comment] 2020-04-13 22:22
sorry for not getting back at you. i can't reproduce this, and will close this issue because it is so old. If you still face this issue please don't hesitate to reopen and provide some more details, ideally an example that reproduces this issue.

**Closed by tkloht** 2020-04-13 22:22 UTC
